

const TRANSACTION_TYPES_CONFIG = {
  PARTNER_TO_PARTNER: "PARTNER_TO_PARTNER",
  RECORD_AMOUNT: "RECORD_AMOUNT",
  LOAN_DISBURSEMENT: "LOAN_DISBURSEMENT",
  LOAN_REPAYMENT: "LOAN_REPAYMENT",
  AUCTION_PAYOUT: "AUCTION_PAYOUT",
  CHIT_CONTRIBUTION: "CHIT_CONTRIBUTION",
  DOCUMENT_CHARGE: "DOCUMENT_CHARGE",
};



module.exports = {
  TRANSACTION_TYPES_CONFIG,
}