services:
  - type: web
    name: microfinance-app
    env: docker
    dockerfilePath: Dockerfile
    buildCommand: |
      docker build --build-arg DATABASE_URL=$DATABASE_URL -t microfinance-app .
    startCommand: docker run -p 3000:3000 microfinance-app
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_1dHUbcClOP3S@ep-royal-shape-a8weg8xz-pooler.eastus2.azure.neon.tech/neondb?sslmode=require
        fromDatabase: false
